Fix/tests
blockcoders/near-rpc-providers pull request #17
Opened 2021-12-15 22:11 UTC by AnnRiera

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/blockcoders/near-rpc-providers/blob/main/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2021-12-15 22:19 UTC, jarcodallo requested changes
Use `.to.be.rejectedWith(Error)` helper to expect an error

2021-12-15 22:19 UTC, jarcodallo commented on src/near-rpc-provider.spec.ts
> +    })
You can do this in one line like this:
```ts
await expect(() => provider.getBalance('')).to.be.rejectedWith(Error)
```

2021-12-15 22:19 UTC, jarcodallo commented on src/near-rpc-provider.spec.ts
> +    })
You can do this in one line like this:
```ts
await expect(() => provider.getBlock('')).to.be.rejectedWith(Error)
```

2021-12-15 22:19 UTC, jarcodallo commented on src/near-rpc-provider.spec.ts
> +    })
You can do this in one line like this:
```ts
await expect(() => provider.getGasPrice()).to.be.rejectedWith(Error)
```

2021-12-15 22:19 UTC, jarcodallo commented on src/near-rpc-provider.spec.ts
> +  })
You can do this in one line like this:
```ts
await expect(() => provider.getCode('', '')).to.be.rejectedWith(Error)
```

2021-12-15 22:54 UTC, AnnRiera commented on src/near-rpc-provider.spec.ts
> +  })
Got it!

2021-12-15 22:54 UTC, AnnRiera commented on src/near-rpc-provider.spec.ts
> +    })
Roger that!

2021-12-15 22:55 UTC, AnnRiera commented on src/near-rpc-provider.spec.ts
> +    })
Copy!

2021-12-15 22:55 UTC, AnnRiera commented on src/near-rpc-provider.spec.ts
> +    })
Ok!

2021-12-16 18:33 UTC, jarcodallo approved these changes
LGTM

2021-12-16 18:33 UTC, merged